version: "3.9"
services:
  web-octane:
    image: irriga/php82-laravel-2023:octane
    container_name: irriga-laravel
    restart: always
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
      args:
        PHP_VERSION: '8.2.10-bullseye'
    volumes:
      - .:/var/www/app
    ports:
      - "8093:80" #http
      - "4444:443" #https
